version: "3.8"

volumes:
  opensearch-data:

services:

  opensearch:
    image: inline-opensearch:latest # This should be the same image used for opensearch-node1 to avoid issues
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: opensearch
    environment:
      - discovery.type=single-node
      # - cluster.name=opensearch-cluster
      # - node.name=opensearch-opensearch
      # - discovery.seed_hosts=opensearch
      # - cluster.initial_cluster_manager_nodes=opensearch
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD='Av2ohkai[koo4aev'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    # networks:
    #   - opensearch-net
    
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    depends_on:
      - opensearch
    # networks:
    #   - opensearch-net
